version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gestao-alunos-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - gestao-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gestao_alunos
      DB_USERNAME: root
      DB_PASSWORD: root
    entrypoint: ["/bin/sh", "/var/www/gestao_alunos/entrypoint.sh"]


  web:
    image: nginx:alpine
    container_name: gestao-alunos-web
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gestao-network

  db:
    image: mysql:5.7
    container_name: gestao-alunos-db
    environment:
      MYSQL_DATABASE: gestao_alunos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - gestao-network

networks:
  gestao-network:

volumes:
  dbdata:
